services:
  worker:
    build: .
    image: automatic-transcriptions:latest
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_REGION: ${AWS_REGION:-us-east-1}
      WASABI_SRC_BUCKET: ${WASABI_SRC_BUCKET:-}
      WASABI_DST_BUCKET: ${WASABI_DST_BUCKET:-}
      WASABI_PREFIX: ${WASABI_PREFIX:-}
      WASABI_OUTPUT_PREFIX: ${WASABI_OUTPUT_PREFIX:-processed/}
    volumes:
      - ./data:/data
    command: ["process", "--help"]

